language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO==1.9rc1

#    - TOX_ENV=py27-lint
#    - TOX_ENV=py27-docs

matrix:
  fast_finish: true
  exclude:
    - python: 3.5
      env: DJANGO=1.7

install:
  - pip install -U pip setuptools
  - pip install -r requirements/requirements-testing.txt
  - pip install flake8
  - if [[ $DJANGO =~ = ]]; then
    pip install --pre --quiet "Django=$DJANGO";
    else
    pip install --quiet "Django>=$DJANGO,<$DJANGO.99";
    fi

script:
    - ./runtests.py --fast

#after_success:
#    - pip install codecov
#    - codecov -e TOX_ENV
